title: Shinwoo Kim
author: Shinwoo Kim
email: shinwookim@pitt.edu
description: >-
  I am a software developer based in Pittsburgh who is interested in
  computer architecture, distributed/operating systems, and compilers.
baseurl: "/archive/teaching/"
url: "https://shinwookim.github.io"
twitter:
  username: _shinwookim
  card: summary
social:
  name: Shinwoo Kim
  links:
    - https://twitter.com/_shinwookim
    - https://www.instagram.com/_shinwookim
    - https://www.linkedin.com/in/kimshinwoo
    - https://github.com/shinwookim

# Social Profiles
twitter_username: _shinwookim
github_username: shinwookim
instagram_username: _shinwookim
linkedin_username: kimshinwoo

# Build settings
markdown: kramdown
highlighter: rouge

timezone: America/New_York
excerpt_separator: <!--more-->
include:
  - _pages
exclude:
  - styles
collections:
  projects:
    output: true
plugins:
  - jekyll-feed
  - jekyll-spaceship
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
    values:
      seo_description_max_words: 200
      image: https://lp-cms-production.imgix.net/2019-06/b620bbff71a0adb8fd86ee311fdba089-cathedral-of-learning.jpg
